### ISSUE TITLE
crashes while indexing own s3 files

### ISSUE THREAD

**Issue by Tupsi** [SvenWerlen/moulinette-tiles#12]
the current version starts indexing fine, but at some point always throws the following in console.
<img width="575" alt="image" src="https://github.com/SvenWerlen/moulinette-tiles/assets/3730499/2bda57d2-23d9-4a3c-be1b-1f8576981050">

deleting that folder and rerunning indexing only put the error at some other directory (in the new scan).

I had used the some structure with items for a while now and had configured indexing it old style like you once told me on discord (with .mtte files), but deleted these and recreated them in your new gui as I saw the "deprecated" warning in the config.

<img width="769" alt="image" src="https://github.com/SvenWerlen/moulinette-tiles/assets/3730499/e768705d-b689-4e91-a94e-9521df4b4a00">

I also noticed that clicking the eye (toggle source) does NOT exclude that line from getting indexed (which would be what I had figured the button does), but maybe I just do not get the correct idea of that button, so that might be just a layer 8 problem on my end :-)

**Comment by Tupsi** [comment]
seems the indexing does not like spaces in names any longer. I put a _ in between Pathfinder Others (which you can see in the first screenshot) and now the indexing runs through.

**Comment by SvenWerlen** [comment]
Thank you for reporting this!
Can you please confirm which version (moulinette-core) do you use?
Also which S3 provider?

I tried to reproduce it and wasn't able :
![image](https://github.com/SvenWerlen/moulinette-tiles/assets/938060/5d58ec24-c622-4d7d-bc58-02ead8f0ff75)

**Comment by Tupsi** [comment]
interesting that this just works for you:

i was using wasabi as s3 provider with vtt version 11.301 and moulinette core v 11.1.0.

**Comment by Tupsi** [comment]
just tested with vtt 11.302 and core v11.1.1 aqnd nothing changed. 

what settings are you using in the moulinette dialog?

**Comment by Tupsi** [comment]
ok, so I found a difference in how you enter the details for the directory in the moulinette gui.

Using "Auto" or Creatarname with * as Pack option does not work here an produces the shown error. Filling out Creator and Pack does not create the error and results in a correct indexing.

<img width="431" alt="image" src="https://github.com/SvenWerlen/moulinette-tiles/assets/3730499/1d3fe3f4-e180-4484-acba-8fb55b11bae5">

this worked.

while the next screenshot did not:
<img width="430" alt="image" src="https://github.com/SvenWerlen/moulinette-tiles/assets/3730499/0b6bef55-5c94-4512-ae98-f2169bbd9ecb">

BUT (and here it gets weird), if you do the working version first (without the error), then get into the gui again and deleted that line (which should delete the indexed part of it as well) this looks fine first (the entry disappears in the dropdown of tiles).
But if you now add the line again in the way it should produce the error, the error does not show, the indexing is done and the entry shows again in the dropdown (I suspect you do not really rescan because you never have actually deleted that part in the index).

Now if you completely delete the index with the button on the gui and index again the error shows up again, leaving you without an index,


I hope reading that all makes at least sense in the way that you are able to redo the error on your end.

If you wanna debug that further, full free to bug me on discord. Although our different timezones make that hard, I know. :-)

**Comment by SvenWerlen** [comment]
This is super useful. I was able to reproduce by using "*" rather than specifying the pack name.
I fixed it in moulinette-core `v-11.1.2`. Feel free to re-open it if you still have an issue with it.
Note : yes it is intended that deleting the source won't delete it from the index. You might have other worlds which use the same index and you probably don't want to index multiple times the same sources.
