### ISSUE TITLE
Path separators entity-encoded since recently

### ISSUE THREAD

**Issue by DrMcCoy** [SvenWerlen/moulinette-tiles#13]
*EDITED, because I misidentified the bug*

In a recent update, the path separator / in subdirectories is entity-encoded as %2F.

For example, for 
```assets/tiles/Forgotten%20Adventures/Tokens/Spirits/Spirits_Adversaries/Cultist_Mage_Staff_Magic_Spirit_01.png```
it now shows
```assets/tiles/Forgotten%20Adventures/Tokens/Spirits%2FSpirits_Adversaries%2FCultist_Mage_Staff_Magic_Spirit_01.png```

This doesn't happen for images without additional subdirectory (further than creator + pack).

**Comment by SvenWerlen** [comment]
Mmm, this is bad. Looking into this right now.

**Comment by SvenWerlen** [comment]
I'm not able to reproduce it with the FVTT app. However, I know I did some changes to support `#` in filenames that could have caused it. I just released a new version `v-11.1.3` that should fix it.

**Comment by DrMcCoy** [comment]
Yes, this fixes the issue; thanks!

**Comment by SvenWerlen** [comment]
Thanks for confirming it!
