### ISSUE TITLE
Issue dragging from favorites to canvas

### ISSUE THREAD

**Issue by matt-duffy** [SvenWerlen/moulinette-tiles#14]
I have the Forgotten Adventures assets all in an S3 bucket, this all works fine when using the standard moulinette picker and dragging onto the canvas.  But if I mark something as a favourite and then drag it from the favourites pane onto the canvas nothing appears and I see this error in the console.

This is with only Moulinette Core and Tiles enabled as modules.

![image](https://github.com/SvenWerlen/moulinette-tiles/assets/6329577/a25b8be9-e0f0-4446-8006-19f12b617573)

Core Version: 11.315
System: dnd5e 3.1.2 (Atropos) 

Modules: 
...
moulinette-core 12.0.0 (Sven Werlen)
moulinette-gameicons 12.0.0 (Sven Werlen)
moulinette-imagesearch 12.0.0 (Sven Werlen)
moulinette-scenes 12.1.3 (Sven Werlen)
moulinette-sounds 12.1.0 ()
moulinette-tiles 12.1.2 ()
...

**Comment by SvenWerlen** [comment]
Fixed in `v-12.1.3`. Thank you for reporting it!

**Comment by matt-duffy** [comment]
Great stuff thank you, all working nicely for me now!
