### ISSUE TITLE
Drag n drop onto Canvas is often not happening

### ISSUE THREAD

**Issue by franckflo** [SvenWerlen/moulinette-tiles#2]
First, thanks a lot for this wonderful tools, with so many potential uses :)

I noticed this mostly for the Tiles and Image Search function. If I pick to save the item to a Tile and drag n drop the item from either the Tiles or Image Search tab, I see the notification that the image was saved to the Moulinette folder (and I can see the file is indeed saved there with the Windows File Explorer, so that part works), but the items does not show on the canvas. It works fine if I pick to save it as a Token, just not with tiles. Strangely, on the many tries I have seen it work once or twice (even though I was doing the same exact steps). 

I am wondering if there is some kind of conflict with another Module (I have quite a few enabled).  The main module that comes to mind is "Drag Upload" as it allows to drag and drop files from the PC's file system to the FVTT canvas. I will run Find the Culprit tonight to see if that is a conflict indeed, and report my findings.

**Comment by franckflo** [comment]
So after running Find the Culprit, it does not seem to be a conflict with another module, the problem occurs if only the Moulinette modules are enabled. I did however notice that 
- the problem occurs mostly on my World's Landing page: could this be related to that? Since it's not a map, the scene for that landing page has a lot of mapping options disabled.
- if I first download, then drag the image/tile again to the canvas it works, but it seems to download the image twice as a result. Could this be some kind of weird timing issue? 
Note: I'm using Brave as a browser.

**Comment by SvenWerlen** [comment]
Oh, I think I understand your issue. You have to know that Moulinette starts downloading the image when you start dragging the file HOWEVER, you must wait for the message to showup before dropping it on the scene. Because if you drop it before the image was downloaded, Foundry will complain that the image doesn't exist and it will fail. If you try again, it will always work because the file already exists.

Can you try it and confirm before I close this issue?

**Comment by franckflo** [comment]
Yep that's it, you are correct!

**Comment by SvenWerlen** [comment]
Excellent! Thank you for confirming it!
