### ISSUE TITLE
Tiles menu does not open, console error

### ISSUE THREAD

**Issue by MorganeLeCaignec** [SvenWerlen/moulinette-tiles#5]
Since upgrading my foundry install to 8.8, two menus in moulinette have not been working or even opening from the moulinette main menu: Tiles, and Image Search.

The issue is the same with both but Tiles concerns me more since I use it a lot.

It gives this console error when clicking on the button either from the quick menu or the full window with tabs:

```
Foundry VTT | Rendering MoulinetteForge           foundry.js:2033:15


Moulinette Forge Module | Default supportsMode() not implemented           moulinette-forge-module.js:17:13


Error: An error occurred while rendering MoulinetteForge 302: This is not a registered game setting          foundry.js:2006:14
    get foundry.js:1146
    getFooter moulinette-tiles.js:195
    getData moulinette-forge.js:98
    _render foundry.js:2042
    call_wrapped libWrapper-wrapper.js:465
    <anonymous> listeners.js:75
    _render#0 libWrapper-wrapper.js:160
    _render foundry.js:2729
    render foundry.js:2004
    _onNavigate moulinette-forge.js:165
    jQuery 9
    activateListeners moulinette-forge.js:125
    _render foundry.js:2070
    call_wrapped libWrapper-wrapper.js:465
    <anonymous> listeners.js:75
    _render#0 libWrapper-wrapper.js:160
    _render foundry.js:2729
    render foundry.js:2004
    _onNavigate moulinette-forge.js:165
    jQuery 9
    activateListeners moulinette-forge.js:125
    _render foundry.js:2070
    call_wrapped libWrapper-wrapper.js:465
    <anonymous> listeners.js:75
    _render#0 libWrapper-wrapper.js:160
    _render foundry.js:2729
    render foundry.js:2004
    _onNavigate moulinette-forge.js:165
    render foundry.js:2006
    (Async: promise callback)
    render foundry.js:2004
    _onNavigate moulinette-forge.js:165
    jQuery 9
    activateListeners moulinette-forge.js:125
    _render foundry.js:2070
    call_wrapped libWrapper-wrapper.js:465
    <anonymous> listeners.js:75
    _render#0 libWrapper-wrapper.js:160
    _render foundry.js:2729
    render foundry.js:2004
    _onNavigate moulinette-forge.js:165
    jQuery 9
    activateListeners moulinette-forge.js:125
    _render foundry.js:2070
    call_wrapped libWrapper-wrapper.js:465
    <anonymous> listeners.js:75
    _render#0 libWrapper-wrapper.js:160
    _render foundry.js:2729
    render foundry.js:2004
    _onNavigate moulinette-forge.js:165```

**Comment by SvenWerlen** [comment]
Can you confirm that you also updated `moulinette-core` to latest version? This error should not happen and seems to be due to a missing setting.

**Comment by MorganeLeCaignec** [comment]
Oh wow. So a weird Foundry bug I just found. I was hitting "Update All" and it seemed to be latest, but by hitting Update directly on Core it suddenly updated (it was still on 3.0.2).
I have no idea why the Update All updated some of the other moulinette modules and bunch of other modules I have no problem but it seems to have been stuck on a lot of modules, I'm hitting them all manually and a lot of them are updating now.

Maybe some module is so old/broken that it's breaking the Update All, the update report gives me a bunch of "timed out" for some old modules I don't use.

So there's no problem i guess, I just had no idea Core wasn't updating!

**Comment by SvenWerlen** [comment]
Interesting. I've never seen that issue. Good that it works. Thank you for using Moulinette
