### ISSUE TITLE
Import of prefabs and Pathfinder 2e system

### ISSUE THREAD

**Issue by Thobicus** [SvenWerlen/moulinette-tiles#8]
Baileywiki Prefab import is broken in Pathfinder 2e system, as can be seen on the screenshots
<img width="1922" alt="Final result" src="https://user-images.githubusercontent.com/99014846/152506739-75c220d7-3993-468f-aa5b-4ff8a3fbe945.png">
<img width="1922" alt="Start" src="https://user-images.githubusercontent.com/99014846/152506757-0f977f60-f122-4d67-a47d-e3a9f6bfff8c.png">
<img width="1922" alt="errors" src="https://user-images.githubusercontent.com/99014846/152506768-6833f3eb-264d-4700-b011-7f06b079677b.png">

**Comment by SvenWerlen** [comment]
According to my investigations, this seems to be a potential bug in PF2 system.
The system seems to expect some data value which is not available in the Prefab itself. If I try to use it from Baileywiki compendium directly, I get the same error. This indicates that it's not a Moulinette issue but rather a condition that is not properly handled by the system or actor data not compatible with PF2. I know that BW uses D&D 5 for creating the actors data.
![image](https://user-images.githubusercontent.com/938060/152649780-9cd27f09-52a3-40fa-b9e6-77750a85d985.png)

Sorry that I cannot actually do more about it.
If I would know which data is required (in the actor), I can probably implement a workaround for PF2 by filling it during the import.
