### ISSUE TITLE
Generate/serve thumbnails instead of full images

### ISSUE THREAD

**Issue by hjk321** [SvenWerlen/moulinette-tiles#9]
I, as I assume many people, host on a platform with limited bandwidth. Custom token files can become rather large if they're high quality and when you're opening a pack with hundreds of tokens they take a long time to load and use up precious bandwidth.

This could be remedied by utilizing 256x256 thumbnails, which is a good size for previewing a tile before dropping it into the scene. I don't know whether it is more advisable to generate these thumbnails during the indexing process or on the fly as they are requested, but they would be a very important addition to this module.

Cheers.

**Comment by SvenWerlen** [comment]
Hi there!
I understand this issue and the suggestion. However, this is pretty hard to implement in the module itself (generating thumbnails with Javascript) and it would slow down the indexing process. For all those reasons, I'm not planning to implement it. 
Thank you for your understanding.

_Alternative : Moulinette Cloud does this automatically for you. On Dwarf Blacksmith tier or more, you get a 5GB private storage._
